# 三峡大学选课系统配置
username: ""       # 学号
password: ""  # 加密后的密码
grab_interval: 2               # 抢课请求间隔时间(秒)
max_workers: 15                # 最大并发线程数
campus: "01"                   # 校区代码(01:主校区, 02:中区，03:西区,04:压测校区)
advance_time: 50               # 提前开始抢课的时间(秒)